### ISSUE TITLE
[Bug] gsetup.init() function problem

### ISSUE THREAD

**Issue by xuezhicang** [OSGeo/grass#1987]
**Describe the bug**
gsetup.init()  function has problem in the GRASS 8.0.dev (2021)

**To Reproduce**
I am using a python program to create a GRASS GIS mapset.

The error message is:

```
Traceback (most recent call last):
  File "add_d_w_mpi.py", line 132, in <module>
    gisrc=gsetup.init(gisbase, gisdb, "dummy", "PERMANENT")
  File "/umbc/xfs1/mbaker/common/huc_test/Essential_Scripts/HydrographyWorkflow/
Cang/grass_install/grass/grass80/etc/python/grass/script/setup.py", line 326, in
 init
    mapset_path.directory, mapset_path.location, mapset_path.mapset
ValueError: Mapset /umbc/xfs1/mbaker/common/huc_test/Essential_Scripts/Hydrograp
hyWorkflow/Cang/etchedDEM/StrProp/dummy is not valid: </umbc/xfs1/mbaker/common/
huc_test/Essential_Scripts/HydrographyWorkflow/Cang/etchedDEM/StrProp> is not a
valid GRASS Location because PERMANENT Mapset is missing
```

My program works in the GRASS GIS 7.8.6, so I think it is not my program's problem. Could you help figure it out?

Thanks,
Xuezhi Cang

**Comment by wenzeslaus** [comment]
Thanks for reporting this. I fixed that in #1979 (after introducing in earlier with #1829), but did not backport to the 8.0 branch. I'll do that soon.

Besides #1829, see also #1835 and #1838 (or just the latest examples for using [init](https://mybinder.org/v2/gh/OSGeo/grass/main?urlpath=lab%2Ftree%2Fdoc%2Fnotebooks%2Fbasic_example.ipynb)). The grass.script.setup.init function changed significantly and it has a different interface. I hope it will be easier to use than before. (And of course, open issues if you encounter any trouble.)

**Comment by wenzeslaus** [comment]
Backported to 8.0 as 41bb7ce94cd440c8bc60fd258170f4ca165519af.

**Comment by xuezhicang** [comment]
Hello,

I still am still getting error message. I followed your example code and write my version:

```python
import os
import sys
import subprocess
grass8bin = r"/umbc/xfs1/mbaker/common/huc_test/Essential_Scripts/HydrographyWorkflow/Cang/grass_install/grass/bin/grass"
# The gisdb is an empty folder. 
gisdb = r"/umbc/xfs1/mbaker/common/huc_test/Essential_Scripts/HydrographyWorkflow/Cang/etchedDEM/StrProp"

# Ask GRASS GIS where its Python packages are.
gisbase = subprocess.check_output([grass8bin, "--config", "path"], text=True).strip()
os.environ["GISBASE"] = gisbase
sys.path.append(os.path.join(gisbase, "etc", "python"))

import grass.script as gs
import grass.script.setup as gsetup

gsetup.init(gisdb+"/dummy"+"/PERMANENT")
```
The error is:
```

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/umbc/xfs1/mbaker/common/huc_test/Essential_Scripts/HydrographyWorkflow/Cang/grass_install/grass/grass80/etc/python/grass/script/setup.py", line 313, in init
    raise ValueError(_("Path '{path}' does not exist").format(path=path))
ValueError: Path '/umbc/xfs1/mbaker/common/huc_test/Essential_Scripts/HydrographyWorkflow/Cang/etchedDEM/StrProp/dummy/PERMANENT' does not exist

```
I think that the "dummy" folder and "PERMANENT" mapset should be created created by the init function, so I cannot understand why the error message says that the folder does not exist.
 
Could you help me take a look? Thank you.

**Comment by wenzeslaus** [comment]
@xuezhicang I think there is a confusion somewhare about what _init_ should do. It only initializes the session, it _currently_ does not create any data/folder structures.

> I think that the "dummy" folder and "PERMANENT" mapset should be created created by the init function, so I cannot understand why the error message says that the folder does not exist.

The `dummy` folder (which would be the location in the GRASS data hierarchy) and `PERMANENT` sub-folder (the mandatory always-present mapset) are not created automatically by the _init_ function. It never behaved that way. Please, let us know if you used some misleading instructions.

The easiest way to create it is probably calling the executable in as a supbrocess (you already have grass8bin, so you do just another _check_output_ call) and asking it to create a new location with `-c` and `EPSG:XXXX` where `XXXX` is EPSG code of you choice (data).

PRs to add location (and mapset) creation functionality to _init_ are of course welcome.

**Comment by xuezhicang** [comment]
Thank you for your help!
