### ISSUE TITLE
[Bug] [Windows] Crash of the GRASS-GIS 8.3 `v.surf.rst.exe` (OSGeo4W) and Windows module `ntdll.dll`

### ISSUE THREAD

**Issue by carnendil** [OSGeo/grass#3737]
## Describe the bug

As reported [here](https://github.com/qgis/QGIS/issues/57523), running `v.surf.rst` in QGIS on MS Windows 10, results in the following error and the output file is not created:

```
ERROR: Raster map or group <elevationXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX> not found`
```

The problem has been [traced](https://github.com/qgis/QGIS/issues/57523#issuecomment-2130495986) to 

> crash of the GRASS-GIS 8.3 program `v.surf.rst.exe` (from OSGeo4W) and the Windows module `ntdll.dll` on Windows with the following error:

```
Nome registro: Application
Origine:       Application Error
Data:          
ID evento:     1000
Categoria attività:(100)
Livello:       Errore
Parole chiave: Classico
Utente:        N/D
Computer:      
Descrizione:
Nome dell'applicazione che ha generato l'errore: v.surf.rst.exe, versione: 8.3.0.0, timestamp: 0x656ba046
Nome del modulo che ha generato l'errore: ntdll.dll, versione: 10.0.18362.778, timestamp: 0x0c1bb301
Codice eccezione: 0xc0000374
Offset errore 0x00000000000f9229
ID processo che ha generato l'errore: 0x1064
Ora di avvio dell'applicazione che ha generato l'errore: 0x01daae2a1a76729a
Percorso dell'applicazione che ha generato l'errore: C:\OS2019~1\apps\grass\grass83\bin\v.surf.rst.exe
Percorso del modulo che ha generato l'errore: C:\WINDOWS\SYSTEM32\ntdll.dll
ID segnalazione: 0b98d9be-1f83-4919-8618-24bfe91af48b
```

> The issue doesn't occur using GRASS-GIS 7.8.6.

> It seems to me the error is not in QGIS itself but either in GRASS-GIS 8.3 or in the GRASS-GIS 8.3 package provided by OSGeo4W or in the Windows OS.

## To reproduce

1. From the Processing Toolbox in QGIS launch the `v.surf.rst` algorithm.
2. Select the input points layer (a `.gpkg` layer in my case).
3. Select the "Name of the attribute column with values tu be used for approximation". Elevation data column in my case.
4. Select the "Name of the raster map used as a mask". In my case, a `.sdat` raster containing a single polygon. All points are contained within that polygon.
5. For "Interpolated RST", select "Save to file..." and give a name to the output file.
6. For all other outputs (Slope, Aspect, Profile curvature, Tangential curvature, Mean curvature, Deviations, Quadtree segmentation, and Overlapping windows), select "Omit output".
7. Run the algorithm.

### All the algorithm parameters

- Input points layer: `input-points.gpkg`
- Name of the attribute column with values to be used for approximation [optional]: `field_3`
- WHERE conditions of SQL statement without 'where' keyword [optional]: blank { default }
- Name of the raster map used as mask [optional]: `input-mask-taster.sdat`
- Tension parameter [optional]: `40.000000` { default }
- Smooting parameter [optional]: Not established { default }
- Name of the attribute column with smoothing parameters [optional]: blank { default }
- Maximum number of points in a segment [optional]: `40` { default }
- Minimum number of points for approximation in a segment (>segmax) [optional]: `300` { default }
- Minimum distance between points (to remove almost identical points) [optional]: Not established { default }
- Maximum distance between points on isoline (to insert additional points) [optional]: Not established { default }
- Conversion factor for values used for approximation [optional]: `1.000000` { default }
- Anisotropy angle (in degrees counterclockwise from East) [optional]: Not established { default }
- Anisotropy scaling factor [optional]: Not established { default }
- &#x2610; Use scale dependent tension { default: not selected }
- &#x2610; Output partial derivatives instead of topographic parameters { default: not selected }
- Advanced parameters:
  - Extensión de la región de GRASS GIS 7 [opcional]: Not established { default }
  - Tamaño de la celda de la región de GRASS GIS 7 (dejar 0 para predeterminado): `0.000000` { default }
  - Opciones de formato de los ráster de salida (createopt) [optional]. blank { default }
  - Opciones de metadatos de formato de los ráster de salida (metaopt) [optional]: blank { default }
  - v.in.ogr tolerancia de autotensado (-1 = sin ensamblado): `-1.000000` { default }
  - v.in.ogr área mínima: `0.000100` { default }
  - v.out.ogr tipo de salida: `auto` { default }
  - v.out.ogr muestra las opciones de la fuente de datos (dsco) [optional]: blank { default }
  - v.out.ogr muestra las opciones de la capa (lco) [optional]: blank { default }
  - &#x2610; Exportar también objetos sin categoría (no etiquetados). De lo contrario solo se exportan los objetos con categoría { default: not selected }
- Interpolated RST [optional] -> Save to file...: `output-raster.sdat`  { sdat file type selected by default }
- &#x2611; Open output file after running the algorithm
- Slope [optional] -> Omit output
- Aspect [optional] -> Omit output
- Profile curvature [optional] -> Omit output
- Tangential curvature [optional] -> Omit output
- Mean curvature [optional] -> Omit output
- Deviations [optional] -> Omit output
- Quadtree Segmentation [optional] -> Omit output
- Overlapping Windows [optional] -> Omit output

## Expected behavior
Creation of a raster with the interpolated RST.

## System description
- Operating System: Windows 10
- GRASS GIS version: 8.3.2

- details about further software components

|                            |                         |                                              |                  |
|-------------------|-----------------|--------------------------------|------------|
| Versión de QGIS | 3.34.6-Prizren | Revisión del código de QGIS | 623828f5 |
| Versión Qt          | 5.15.13            |     |     |
| Versión de Python | 3.12.3           |     |     |
| Versión de GDAL/OGR | 3.8.5      |     |     |
| Versión de PROJ | 9.4.0                |     |     |
| Versión del registro de base de datos EPSG | v11.004 (2024-02-24) |     |     |
| Versión de GEOS | 3.12.1-CAPI-1.18.1 |     |     |
| Versión de SQLite | 3.45.1           |     |     |
| Versión de PDAL | 2.6.3              |     |     |
| Versión del cliente de PostgreSQL | 16.2 |     |     |
| Versión de SpatiaLite | 5.1.0       |     |     |
| Versión de QWT | 6.2.0               |     |     |
| Versión de QScintilla2 | 2.14.1    |     |     |
| Versión del SO    | Windows 10 Version 2009 |     |     |
|                            |                         |                                              |                  |
| Complementos activos de Python |     |     |     |
| LAStools             | 2.1.0                 |     |     |
| processing_saga_nextgen | 1.0.0  |     |     |
| QuickOSM          | 2.2.3                 |     |     |
| quick_map_services | 0.19.34        |     |     |
| db_manager       | 0.1.20               |     |     |
| grassprovider     | 2.12.99             |     |     |
| MetaSearch        | 0.3.6                 |     |     |
| processing          | 2.12.99            |     |     |

## Additional context
I also tried with a different dataset, one for which in Feb. 2023 (possibly QGIS 3.28) the very same procedure had worked perfectly. This time I got the same error described above. It shows that is not a problem with the data, but QGIS/GRASS behaving differently.

The algorithm ran without major problems in Ubuntu (same data, same QGIS version, GRASS 8.3.0)

**Comment by echoix** [comment]
I wanted to reproduce with an nightly build of the upcoming 8.4, but I can't get an installation launching for now (bugs are filed in).

**Comment by agiudiceandrea** [comment]
The issue occurs also using GRASS-GIS 8.4.0-dev f4d8c62ac (OSGeo4W).

**Comment by echoix** [comment]
So it's still a valid bug to look into.

**Comment by echoix** [comment]
Hmm.. I'm not able to make the module run correctly, but it isn't because of loading a dll or segfault or the sort.
I'm using grass-dev 8.4-313-f4d8c62ac-1 from OSGeo4W, without QGIS, on a fresh OS install (windows sandbox), + installed missing gdal308-runtime + patch of #3732

I set the projection to WGS84 UTM17N as the data from the issue in the QGIS repo.

![image](https://github.com/OSGeo/grass/assets/27212526/3df6c1d5-d64b-4918-bf4e-97c35a9e9447)

I don't know what the `Interpolated RST [optional] -> Save to file...: output-raster.sdat { sdat file type selected by default }` option mapped to, but I chose the options as below, and got the result as above.


![image](https://github.com/OSGeo/grass/assets/27212526/1e042f29-baa5-4770-a110-52acedff7773)
![image](https://github.com/OSGeo/grass/assets/27212526/9193d916-af31-4115-a65c-0843af7b0f8b)
![image](https://github.com/OSGeo/grass/assets/27212526/d5607de3-3add-418d-b6b5-6283bffd1cef)
![image](https://github.com/OSGeo/grass/assets/27212526/f70f9b1c-db39-437f-8f98-4dde9b2216ae)
![image](https://github.com/OSGeo/grass/assets/27212526/ac64e49a-f83a-47a0-8f68-72f4b512ba19)



So, is it true that the data points aren't in the mask, or that's a problem?

**Comment by neteler** [comment]
@echoix: does the [v.surf.rst manual page example](https://grass.osgeo.org/grass-stable/manuals/v.surf.rst.html#example) work for you?

**Comment by echoix** [comment]
> @echoix: does the [v.surf.rst manual page example](https://grass.osgeo.org/grass-stable/manuals/v.surf.rst.html#example) work for you?

Not really.

After making sure I had the north carolina dataset, and found out how to switch to it, it was r.random at the beginning that errored out. It absolutely wanted `-s` or seed, exited non-zero.

Adding that, I was able to go up to the first v.surf.rst call. A couple warnings, overshoots, and finishes non-zero.

```
498|84.681931
499|76.610321
500|97.182198
(Sun May 26 17:20:50 2024) Command finished (1 sec)                             
(Sun May 26 17:20:59 2024)                                                      
v.surf.rst elevrand zcol=value elevation=elev_full                              
Reading features from vector map ...
WARNING: There are less than 600 points for interpolation. No segmentation is necessary, to run the program faster set segmax=600 (see manual)
Processing all selected output files will require
7.73 MB of disk space for temp files.
Processing segments in parallel...
Starting parallel work
G_ludcmp() failed! n=0  d=0.00
WARNING: Overshoot - increase in tension suggested. Overshoot occurs at (456,339) cell. Z-value 60032.884815, zmin 57.113735, zmax 155.267105.
(Sun May 26 17:21:11 2024) Command ended with non-zero return code 3221226356 (11 sec)
(Sun May 26 17:21:25 2024)                                                      
r.colors elev_full raster=elevation                                             
ERROR: Raster map <elev_full> not found
(Sun May 26 17:21:27 2024) Command ended with non-zero return code 1 (0 sec)    
``` 

<details><summary>Details</summary>
<p>


```
(Sun May 26 17:20:04 2024)                                                      
g.region raster=elevation -p                                                    
projection: 99 (Lambert Conformal Conic)
zone:       0
datum:      nad83
ellipsoid:  a=6378137 es=0.006694380022900787
north:      228500
south:      215000
west:       630000
east:       645000
nsres:      10
ewres:      10
rows:       1350
cols:       1500
cells:      2025000
(Sun May 26 17:20:05 2024) Command finished (0 sec)                             
(Sun May 26 17:20:12 2024)                                                      
r.random elevation vector_output=elevrand n=500                                 
WARNING: Please update the usage of <r.random>: option <vector_output> has been renamed to <vector>
Creates randomly placed raster cells or vector points
Usage:
 r.random [-snzb] input=name [cover=name] npoints=number[%]
   [raster=name] [vector=name] [seed=value] [--overwrite]
[--help]
   [--verbose] [--quiet] [--ui]
Flags:
  -s   Generate random seed (result is non-deterministic)
  -n   Generate points also for NULL cells
  -z   Generate vector points as 3D points
  -b   Do not build topology
Parameters:
    input   Name of input raster map
    cover   Name of cover raster map
  npoints   The number of points (or cells) to generate
   raster   Name for output raster map
   vector   Name for output vector map
     seed   Seed for rand() function
ERROR: At least one of the following options is required:
<seed> and <-s>
(Sun May 26 17:20:13 2024) Command ended with non-zero return code 1 (0 sec)    
(Sun May 26 17:20:25 2024)                                                      
r.random elevation vector_output=elevrand n=500 -s                              
WARNING: Please update the usage of <r.random>: option <vector_output> has been renamed to <vector>
Collecting Stats...
Writing vector map <elevrand> ...
Building topology for vector map <elevrand@PERMANENT>...
Registering primitives...
(Sun May 26 17:20:27 2024) Command finished (1 sec)                             
(Sun May 26 17:20:37 2024)                                                      
v.info -c elevrand                                                              
INTEGER|cat
DOUBLE PRECISION|value
Displaying column types/names for database connection of layer <1>:
(Sun May 26 17:20:39 2024) Command finished (0 sec)                             
(Sun May 26 17:20:48 2024)                                                      
v.db.select elevrand                                                            
cat|value
1|132.965866
2|128.907272
3|86.381989
4|71.456177
5|127.36245
6|151.163696
7|136.420746
8|142.311371
9|127.20462
10|126.189056
11|85.319153
12|87.058777
13|98.887451
14|80.508537
15|57.113735
16|116.514191
17|57.18261
18|122.41436
19|116.78801
20|89.701691
21|102.448624
22|136.713104
23|131.676056
24|97.604576
25|122.695023
26|122.535904
27|83.303314
28|147.572891
29|131.226562
30|137.449249
31|120.003113
32|130.987839
33|116.740189
34|69.073097
35|128.595459
36|75.018166
37|147.535034
38|112.19326
39|119.223328
40|81.829445
41|139.86618
42|133.971252
43|135.781128
44|130.958221
45|144.500931
46|115.822182
47|83.518631
48|80.948753
49|138.359314
50|134.856308
51|133.229172
52|153.153259
53|86.682678
54|133.656937
55|144.807388
56|151.406616
57|82.303757
58|143.204956
59|137.478958
60|146.823822
61|152.427002
62|141.057938
63|142.593185
64|146.972046
65|132.624588
66|149.157883
67|149.156143
68|85.189369
69|134.50885
70|131.824768
71|145.033768
72|149.330475
73|98.017487
74|126.304573
75|101.036552
76|142.861145
77|123.423744
78|129.143448
79|105.090195
80|104.210709
81|131.523117
82|91.729568
83|128.231277
84|142.152802
85|98.371674
86|144.853836
87|118.644768
88|141.5103
89|130.001572
90|101.026886
91|101.573914
92|115.022476
93|101.922478
94|145.851868
95|126.784332
96|139.404556
97|129.725281
98|155.267105
99|102.72403
100|98.539749
101|108.994209
102|93.716629
103|101.251083
104|137.710175
105|106.33802
106|139.097656
107|109.06749
108|124.37101
109|134.871628
110|146.766541
111|139.221252
112|130.122467
113|101.615501
114|138.778275
115|128.196884
116|147.730804
117|89.25631
118|96.637512
119|135.857452
120|122.169731
121|106.057724
122|120.401726
123|109.576149
124|119.858444
125|127.103882
126|127.136719
127|120.634178
128|87.987823
129|92.627258
130|124.595139
131|102.842163
132|133.101852
133|109.663399
134|146.493927
135|84.448387
136|139.654373
137|98.123283
138|96.564255
139|145.289383
140|112.156075
141|77.807449
142|115.425255
143|79.309486
144|91.69001
145|133.145218
146|107.770363
147|133.620239
148|86.145866
149|111.738091
150|88.85321
151|115.162048
152|142.635315
153|144.147278
154|133.854141
155|140.286789
156|149.69487
157|74.691757
158|89.467972
159|137.939896
160|127.02813
161|108.614456
162|90.149681
163|97.184288
164|142.449921
165|92.13813
166|133.730972
167|67.585419
168|80.922035
169|149.090134
170|125.985405
171|144.270493
172|90.674072
173|132.301575
174|138.92453
175|145.929749
176|103.555107
177|81.528412
178|76.930183
179|82.216377
180|77.265244
181|79.363342
182|102.085472
183|125.976952
184|78.907944
185|102.656815
186|87.540344
187|139.165482
188|73.162018
189|143.172577
190|74.62043
191|84.46405
192|122.380219
193|66.91951
194|73.289185
195|66.171074
196|122.267769
197|126.566452
198|101.56337
199|144.090088
200|127.472023
201|70.464348
202|77.708252
203|76.997299
204|76.11116
205|115.310814
206|91.311081
207|77.494537
208|69.719482
209|117.274559
210|104.245499
211|140.263611
212|96.594284
213|137.821457
214|104.227448
215|100.169312
216|132.025864
217|104.869934
218|73.061012
219|123.113724
220|140.244415
221|73.505783
222|131.612625
223|108.970688
224|120.185417
225|133.108109
226|143.582489
227|139.969925
228|138.583481
229|138.973175
230|122.645767
231|126.597816
232|138.694717
233|88.84539
234|126.741859
235|134.526428
236|115.87944
237|134.645569
238|138.061081
239|90.173088
240|133.016037
241|108.933235
242|123.931274
243|88.895866
244|115.2733
245|132.211487
246|139.058151
247|80.609596
248|142.984985
249|125.182281
250|125.382156
251|81.196823
252|145.697922
253|123.709373
254|143.491669
255|142.381409
256|140.233337
257|125.852623
258|121.640594
259|133.86882
260|128.500793
261|139.58313
262|138.995636
263|134.13858
264|133.83432
265|128.867096
266|124.851677
267|138.081467
268|136.231949
269|137.429916
270|118.26947
271|137.152817
272|88.800232
273|131.414932
274|85.943237
275|123.135117
276|113.8284
277|123.228508
278|119.643997
279|111.820282
280|121.126633
281|119.202187
282|124.779831
283|117.156784
284|100.368141
285|108.553009
286|98.805099
287|101.547424
288|132.41217
289|115.754089
290|105.377151
291|92.707214
292|110.057899
293|97.233681
294|91.048584
295|118.209518
296|125.201324
297|127.402588
298|90.332214
299|102.309822
300|125.084145
301|80.707199
302|127.977852
303|102.01194
304|93.311424
305|125.666664
306|97.950005
307|106.637367
308|115.674568
309|96.895782
310|123.183243
311|126.973473
312|101.926361
313|135.958328
314|121.111137
315|119.657417
316|118.318092
317|88.754326
318|97.565727
319|123.079666
320|116.878433
321|104.701057
322|101.834923
323|120.030388
324|99.234016
325|112.327911
326|96.925148
327|96.4944
328|91.690735
329|110.280365
330|93.72876
331|98.697594
332|87.118332
333|107.70256
334|90.952293
335|99.57357
336|105.180229
337|109.853127
338|97.518326
339|97.541336
340|94.28334
341|119.479973
342|91.909096
343|95.672043
344|111.726242
345|103.104683
346|134.398529
347|120.799637
348|105.667587
349|109.035957
350|105.426521
351|102.946007
352|108.185661
353|90.233337
354|117.896362
355|130.135742
356|123.809044
357|93.744957
358|125.194466
359|92.890579
360|102.591522
361|104.300407
362|99.616302
363|122.050484
364|92.654205
365|103.229515
366|97.516762
367|108.694214
368|98.878479
369|118.394409
370|91.655945
371|108.200874
372|85.143898
373|83.027977
374|96.14122
375|97.053726
376|82.725716
377|118.783264
378|96.776459
379|80.493309
380|114.172646
381|80.022537
382|106.234116
383|99.066444
384|112.285713
385|123.105766
386|109.63868
387|106.648338
388|90.956078
389|114.149483
390|98.802895
391|132.194473
392|132.083344
393|111.086937
394|96.958099
395|118.286003
396|136.471191
397|111.666756
398|99.448708
399|123.775139
400|113.691566
401|84.483566
402|127.307281
403|128.90358
404|105.082443
405|103.182381
406|88.597267
407|115.880623
408|101.894447
409|127.035484
410|88.94236
411|102.074715
412|80.696754
413|102.629494
414|101.061073
415|116.844223
416|127.572151
417|106.883774
418|111.224815
419|112.144165
420|124.052292
421|89.640793
422|124.773628
423|111.622765
424|123.466782
425|97.388397
426|121.514549
427|92.970253
428|99.377228
429|114.774277
430|104.193283
431|95.457382
432|97.449112
433|77.277344
434|115.783409
435|91.517555
436|98.041595
437|86.717262
438|106.335266
439|80.79763
440|111.761986
441|92.157341
442|93.973183
443|99.334709
444|112.916428
445|91.899155
446|90.165771
447|99.716728
448|96.459503
449|117.470169
450|105.691216
451|103.628479
452|100.303757
453|85.802246
454|100.266838
455|109.544151
456|108.879761
457|92.719437
458|103.65979
459|94.03418
460|85.77179
461|78.316025
462|85.750175
463|92.249741
464|101.242851
465|87.172035
466|100.082809
467|105.55867
468|102.866341
469|111.539352
470|143.720688
471|97.155807
472|102.192741
473|102.626747
474|138.356552
475|126.24369
476|95.619118
477|98.189384
478|85.741287
479|85.254494
480|81.924812
481|87.108551
482|77.516083
483|127.148499
484|135.151962
485|85.416809
486|85.979874
487|111.376022
488|85.589722
489|93.145378
490|89.797783
491|98.320824
492|138.978958
493|127.101845
494|78.252792
495|92.530853
496|119.173264
497|100.173149
498|84.681931
499|76.610321
500|97.182198
(Sun May 26 17:20:50 2024) Command finished (1 sec)                             
(Sun May 26 17:20:59 2024)                                                      
v.surf.rst elevrand zcol=value elevation=elev_full                              
Reading features from vector map ...
WARNING: There are less than 600 points for interpolation. No segmentation is necessary, to run the program faster set segmax=600 (see manual)
Processing all selected output files will require
7.73 MB of disk space for temp files.
Processing segments in parallel...
Starting parallel work
G_ludcmp() failed! n=0  d=0.00
WARNING: Overshoot - increase in tension suggested. Overshoot occurs at (456,339) cell. Z-value 60032.884815, zmin 57.113735, zmax 155.267105.
(Sun May 26 17:21:11 2024) Command ended with non-zero return code 3221226356 (11 sec)
(Sun May 26 17:21:25 2024)                                                      
r.colors elev_full raster=elevation                                             
ERROR: Raster map <elev_full> not found
(Sun May 26 17:21:27 2024) Command ended with non-zero return code 1 (0 sec)    
Failed to run command 'd.rast map=elev_full'. Details:                          
                                                                                
GRASS_INFO_ERROR(6460,1): Raster map <elev_full> not found                      
GRASS_INFO_END(6460,1)                                                          
(Sun May 26 17:26:53 2024)                                                      
# interpolation based on subset of points (only those over 1300m/asl)           
'#' is not recognized as an internal or external command,
operable program or batch file.
(Sun May 26 17:26:54 2024) Command ended with non-zero return code 1 (0 sec)    
(Sun May 26 17:27:03 2024)                                                      
v.surf.rst elevrand zcol=value elevation=elev_partial where=value > 1300        
Reading features from vector map ...
WARNING: Strip exists with insufficient data
WARNING: Zero points in the given region
ERROR: Input failed
(Sun May 26 17:27:04 2024) Command ended with non-zero return code 1 (1 sec)    
(Sun May 26 17:27:14 2024)                                                      
r.colors elev_partial raster=elevation                                          
ERROR: Raster map <elev_partial> not found
(Sun May 26 17:27:15 2024) Command ended with non-zero return code 1 (0 sec)    
Failed to run command 'd.rast map=elev_partial'. Details:                       
                                                                                
GRASS_INFO_ERROR(2648,1): Raster map <elev_partial> not found                   
GRASS_INFO_END(2648,1)                                                          
Failed to run command 'd.rast map=elev_full'. Details:                          
                                                                                
GRASS_INFO_ERROR(164,1): Raster map <elev_full> not found                       
GRASS_INFO_END(164,1)                                                           
Failed to run command 'd.rast map=elev_partial'. Details:                       
                                                                                
GRASS_INFO_ERROR(4804,1): Raster map <elev_partial> not found                   
GRASS_INFO_END(4804,1)                                                          

``` 



</p>
</details> 


![image](https://github.com/OSGeo/grass/assets/27212526/4ced581b-3c9c-4cbb-8016-a8311dbe9163)

**Comment by agiudiceandrea** [comment]
v.surf.rst doesn't crash, with the same inputs and parameters, using GRASS-GIS 7.8.6.

**Comment by agiudiceandrea** [comment]
> installed missing gdal308-runtime

@echoix, see https://trac.osgeo.org/osgeo4w/ticket/835.

**Comment by echoix** [comment]
Can you link in that ticket issues https://github.com/OSGeo/grass/issues/3738 and https://github.com/OSGeo/grass/issues/3739? I'm not sure my trac credentials are still working right now.

**Comment by neteler** [comment]
> After making sure I had the north carolina dataset, and found out how to switch to it, it was r.random at the beginning that errored out. It absolutely wanted `-s` or seed, exited non-zero.

I have corrected/updated the v.surf.rst example in #3743.

**Comment by agiudiceandrea** [comment]
@echoix, the gdal308/gdal309 OSGeo4W packaging issue is fixed now since grass-dev-8.4-314-f3ccff668-1.

**Comment by echoix** [comment]
> The issue occurs also using GRASS-GIS 8.4.0-dev f4d8c62ac (OSGeo4W).

I have a question about this. How did you test that to get this fact?
If it was through QGIS, how do you know that installing grass-dev 8.4.0-dev f4d8c62ac (OSGeo4W) is enough for QGIS to pick it up correctly?

**Comment by agiudiceandrea** [comment]
> How did you test that to get this fact?

I installed GRASS-GIS 8.4.0-dev https://github.com/OSGeo/grass/commit/f4d8c62acd9bb6a65854a111ea73380f7760b838 (grass-dev 8.4-313-f4d8c62ac-1 package) on Windows 10 Home 64-bit using he OSGeo4W Setup adding the gdal308-runtime package and patching the tree.py file as per https://github.com/OSGeo/grass/pull/3732, Then I used the GRASS-GIS 8.4.0-dev GUI and executed v.surf.rst with the layers and parameters provided by you.

**Comment by neteler** [comment]
> > @echoix: does the [v.surf.rst manual page example](https://grass.osgeo.org/grass-stable/manuals/v.surf.rst.html#example) work for you?
> 
> Not really.

It's now fixed in "main".

**Comment by hellik** [comment]
trying it with

```
GRASS version: 8.5.0dev                                                         
Code revision: 3c66b4f08                                                        
Build date: 2024-06-15                                                          
Build platform: x86_64-w64-mingw32                                              
GDAL: 3.9.0                                                                     
PROJ: 9.4.0                                                                     
GEOS: 3.12.2                                                                    
SQLite: 3.45.1                                                                  
Python: 3.12.4                                                                  
wxPython: 4.2.1                                                                 
Platform: Windows-11-10.0.22631-SP0 (OSGeo4W)
```

antivirus/firewall complains about v.surf.rst.exe.

could be the original report also related to antivirus/firewall ?

**Comment by agiudiceandrea** [comment]
@hellik, on a Windows 10 Home 64-bit version 1903 build 18362.778 without any antivirus/firewall software running, the issue still occurs using GRASS-GIS version 8.5.0dev 0b0cffce0 (OSGeo4W): v.surf.rst.exe crashes with the input layers and parameters provided at https://github.com/qgis/QGIS/issues/57523#issuecomment-2130281545.

```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2024-06-16T14:29:20.461583500Z" /> 
  <EventRecordID>199984</EventRecordID> 
  <Channel>Application</Channel> 

  <Security /> 
  </System>
- <EventData>
  <Data>v.surf.rst.exe</Data> 
  <Data>8.5.0.0</Data> 
  <Data>666e197e</Data> 
  <Data>ntdll.dll</Data> 
  <Data>10.0.18362.778</Data> 
  <Data>0c1bb301</Data> 
  <Data>c0000374</Data> 
  <Data>00000000000f9229</Data> 
  <Data>3da4</Data> 
  <Data>01dabff992c76bd4</Data> 
  <Data>C:\OSF9FA~1\apps\grass\grass85\bin\v.surf.rst.exe</Data> 
  <Data>C:\WINDOWS\SYSTEM32\ntdll.dll</Data> 
  <Data>c235f87a-fbd9-4860-83a9-4fe7969d05ab</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

```

```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2024-06-16T14:29:20.461583500Z" /> 
  <EventRecordID>199984</EventRecordID> 
  <Channel>Application</Channel> 
  <Security /> 
  </System>
- <EventData>
  <Data>v.surf.rst.exe</Data> 
  <Data>8.5.0.0</Data> 
  <Data>666e197e</Data> 
  <Data>ntdll.dll</Data> 
  <Data>10.0.18362.778</Data> 
  <Data>0c1bb301</Data> 
  <Data>c0000374</Data> 
  <Data>00000000000f9229</Data> 
  <Data>3da4</Data> 
  <Data>01dabff992c76bd4</Data> 
  <Data>C:\OSF9FA~1\apps\grass\grass85\bin\v.surf.rst.exe</Data> 
  <Data>C:\WINDOWS\SYSTEM32\ntdll.dll</Data> 
  <Data>c235f87a-fbd9-4860-83a9-4fe7969d05ab</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
  <Provider Name="Windows Error Reporting" /> 
  <EventID Qualifiers="0">1001</EventID> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2024-06-16T14:29:23.251755900Z" /> 
  <EventRecordID>199986</EventRecordID> 
  <Channel>Application</Channel> 

  <Security /> 
  </System>
- <EventData>
  <Data>1906747485877836679</Data> 
  <Data>4</Data> 
  <Data>APPCRASH</Data> 
  <Data>Non disponibile</Data> 
  <Data>0</Data> 
  <Data>v.surf.rst.exe</Data> 
  <Data>8.5.0.0</Data> 
  <Data>666e197e</Data> 
  <Data>StackHash_30cd</Data> 
  <Data>10.0.18362.778</Data> 
  <Data>0c1bb301</Data> 
  <Data>c0000374</Data> 
  <Data>PCH_77_FROM_ntdll+0x000000000009CBC4</Data> 
  <Data /> 
  <Data /> 
  <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFDA8.tmp.dmp \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFF30.tmp.WERInternalMetadata.xml \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFF60.tmp.xml \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFF6F.tmp.csv \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFFDE.tmp.txt</Data> 
  <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_v.surf.rst.exe_7676a37ce65155b079b3ae7028ca59b793e3633d_4d9243d9_6bf96f05-efdb-4ce3-8270-0f4db5c30e22</Data> 
  <Data /> 
  <Data>0</Data> 
  <Data>c235f87a-fbd9-4860-83a9-4fe7969d05ab</Data> 
  <Data>268435456</Data> 
  <Data>8fc689e424817ea4ea7620bc6c1e1b87</Data> 
  <Data>0</Data> 
  </EventData>
  </Event>
```
